# Generated by Django 5.2.dev20240704183052 on 2024-07-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
    ]
